### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by JoshuaKasa** [vivaansinghvi07/dreamberd-interpreter#15]
Hey! Amazing job, I love this!

I was wondering tho, how does this interpreter work? Does it make an AST out of the code and then interprets the AST? 

What strategy have you used for making it? I would like to receive a in depth explanation of how the interpreter works rather than a few lines as a response.

Thank you!

**Comment by JoshuaKasa** [comment]
glad to hear that! I'm writing a language myself, mine is transpiled tho, so in case I'll make a interpreted one, I'll know how to do it properly lol.

**Comment by vivaansinghvi07** [comment]
Sorry for the late response, but here is how I made this: 

Just to preface, I didn't use a tutorial (except for one to figure out how to get started in the process that I'll detail in the next section), so the way I did everything may not be the best way to do things. 

## Tokenizing

From knowledge about other things, I figured the best way to start was to organize the code into `tokens`. In my code, a token is defined as the following:

```python3
@dataclass(unsafe_hash=True)
class Token():
    type: TokenType
    value: str 
    line: int = field(hash=False)
    col: int = field(hash=False)
```

The important parts are `type` and `value`. `type` keeps track of what kind of "thing" a token is within the program. Is something a `L_CURLY` (e.g. `{`), a `STRING`, a `NAME` (something like what a variable would be recognized), or a `ADD` (plus sign). To do this step, the code is simply went through character by character, building a token whenever appropriate. You can see the code for this in the function [here](https://github.com/vivaansinghvi07/dreamberd-interpreter/blob/main/dreamberd/processor/lexer.py#L67).

**Note**: For your language, if you do what I did, you may want another type for `KEYWORD`. Since DreamBerd keywords can be overwritten, I figured it would be kind of pointless to do this. 

## Parsing

The next step is to determine what kind of statement each statement is, so that you can run each one properly. In your language, you will probably be able to determine this before running actual code. However, in DreamBerd, I had to generate a list of **possible** statement types, and determine which type was actually valid at runtime. This is something I may change to make more streamlined. You can see the code for this in [this file](https://github.com/vivaansinghvi07/dreamberd-interpreter/blob/main/dreamberd/processor/syntax_tree.py). 

Another key thing about organizing code is parsing expressions. To do this, you first need to recognize there are only a handful of things that can happen in an expression: 

- An object like a list or a map being defined
- A number or name being accessed with just their value, like `3.14` or `my_var`
- A function call
- An operator, whether it be one like a `+` with a left and right, or a `;`, the not operator, which only acts on one value
- A value or list being indexed

You were right in how to organize this - you need to generate a tree structure that turns a list of tokens into an expression tree. This will take a recursive function to do. After determining what takes the most priority in a given run of the function (for example, calling a function on a value and then performing addition, or performing addition and then calling a function on that value), you create a new node in the tree, and then create new child nodes depending on the operation type.

The function that does this is [here](https://github.com/vivaansinghvi07/dreamberd-interpreter/blob/main/dreamberd/processor/expression_tree.py#L80). Additionally, to see how the result, you can evaluate an expression in DreamBerd code, with a high debug status, like this:

```java
print   4-3 ^ 2+1  -  9???
```

Here is what gets printed:

```
Function:
  Name: Token(TokenType.NAME, 'print')
  Arguments:
    Expression:
      Operator: OperatorType.SUB
      Left:
        Expression:
          Operator: OperatorType.EXP
          Left:
            Expression:
              Operator: OperatorType.SUB
              Left:
                Value: Token(TokenType.NAME, '4')
              Right:
                Value: Token(TokenType.NAME, '3')
          Right:
            Expression:
              Operator: OperatorType.ADD
              Left:
                Value: Token(TokenType.NAME, '2')
              Right:
                Value: Token(TokenType.NAME, '1')
      Right:
        Value: Token(TokenType.NAME, '9')
```

If you check this out long enough, you can somewhat see the node structure (I tried to make the printing format understandable, apologies if isn't clear).

## Executing Code

To execute code, what I did was to first determine what the correct statement type is, and then run code according to each type. Check out the spaghetti code [here](https://github.com/vivaansinghvi07/dreamberd-interpreter/blob/main/dreamberd/interpreter.py) to see the functions that make this work. One of the harder parts for this was getting started and figuring out how to store values. I managed this by creating a `Value` base class and other classes on top of the `Value` class to represent each possible type in DreamBerd, like a string, number, list, etc. The code for this is [here](https://github.com/vivaansinghvi07/dreamberd-interpreter/blob/main/dreamberd/builtin.py).

Similar to the last section, executing expressions was done with a recursive function that executes child expressions and then uses their results to evaluate the parent. This function is [here](https://github.com/vivaansinghvi07/dreamberd-interpreter/blob/main/dreamberd/interpreter.py#L726). 

If you want any more details, or an explanation of how each statement is evaluated, how variables are handled, etc., feel free to ask!
